### ISSUE TITLE
Parchment mappings

### ISSUE THREAD

**Issue by lukebemish** [jaredlll08/MultiLoader-Template#13]
Currently, parchment mappings cannot be used on MultiLoader-Template, as the Common project uses vanillagradle, which only supports mojang mappings. This means that when, for instance, navigating code in IntelliJ, code in the Common part will link to the normal, mojmaps-without-parameter-names mappings, even if the Forge or Fabric buildscripts are changed to use parchment. This could be fixed by switching the Common setup to use loom, though I am not sure what other routes might be possible. I do know that there is currently a pull request draft for mapping support open on vanillagradle, but I am not sure what the timeline looks like for that.

**Comment by jaredlll08** [comment]
Assuming it is the same PR, 
https://github.com/SpongePowered/VanillaGradle/pull/47

If I recall correctly, the devs behind it are currently busy with other things unfortunately. 

I currently use https://plugins.jetbrains.com/plugin/17485-scribe, which does help a bit for parameter names, although I do recognize it isn't a solution. 


As for moving common to loom, we don't have any current plans to move away from VanillaGradle (it does exactly what we need and does it well), you of course can make the move to loom yourself in your own project (also look into QuiltFlower if you do, I've heard it is rather good), but right now, the most we may do is add a branch or an example for loom as common.

**Comment by jaredlll08** [comment]
This issue may be relevant to you to get parchment mappings, although it is currently not a fully working solution
https://github.com/jaredlll08/MultiLoader-Template/issues/17

**Comment by lukebemish** [comment]
I've already gotten loom working in common; I can put my solution in that issue though, if it wasn't already working

**Comment by artemisSystem** [comment]
Can this be closed now, since common uses ModDevGradle with NeoForm now?
