### ISSUE TITLE
Setting up Yarn mappings?

### ISSUE THREAD

**Issue by ChrysanthCow** [jaredlll08/MultiLoader-Template#16]
How would I set up yarn mappings for this? I'd like to stick with the mappings I'm familiar with and also setup some older Fabric projects with this template.

Fabric's mapping changing is straightforward but I'm stuck on the Forge part as I require a channel and a MC version, is there an alternative to Architectury Loom that I have to use for such a task?

**Comment by ChrysanthCow** [comment]
Looking at other issues, I'd have to migrate the entire thing to use Loom instead of VanillaGradle, although I am unsure how tricky this is.

Alternatively I'd have to wait for VanillaGradle to support other mappings.

**Comment by ChrysanthCow** [comment]
I've managed to get genSources and --refresh-dependencies running which is nice, going to test a little more to see what else I can do. I just seem to have prepareWorkspace running (which doesn't exist) when I refresh gradle.

(Fixed by deleting .gradle and invalidating caches)

**Comment by ChrysanthCow** [comment]
I'm probably going to close this issue as I can tinker with it in my own time. I'm unsure if I'll be PRing an example to the examples branch, I might though.

If anyone has any questions, feel free to DM me on Discord, Pug#1984

**Comment by ChrysanthCow** [comment]
Reopening as I ran into one last issue.

```
Execution failed for task ':Common:compileJava'.
> java.lang.NoClassDefFoundError: org/objectweb/asm/tree/MethodNode
```

```
Unable to load class 'org.objectweb.asm.tree.MethodNode'.

This is an unexpected error. Please file a bug containing the idea.log file.
```

A class doesn't seem to be found and it's preventing me from starting up a test instance

Happens on both Fabric and Forge as it's an issue in Common

**Comment by ChrysanthCow** [comment]
I've figured that I'm going to wait for other mapping support on vanillagradle

**Comment by Darkhax** [comment]
Hello, thanks for reaching out about this. As you've experienced first hand, convincing the various plugins to use the same unofficial mappings is very tedious. By utilizing the official mojmaps the configuration for our template is simplified and we can avoid non-official plugins and forks. For that reason we are not supporting yarn at this time but would be interested in seeing someone else work this out in the future.

**Comment by jaredlll08** [comment]
This issue details a fix for the missing ASM classes as well as some info on getting Common running on Loom.
https://github.com/jaredlll08/MultiLoader-Template/issues/17
Just note that it is not a complete solution and currently has some issues.
