### ISSUE TITLE
After running both the commands to decompile and genSources, can no longer run fabric client

### ISSUE THREAD

**Issue by The-Code-Monkey** [jaredlll08/MultiLoader-Template#24]
Hi There after following the setup commands, i can no longer run fabric client.

**Comment by jaredlll08** [comment]
What do you mean by "can no longer run"?

Why can't you run? Does the game crash? Are the run configs gone? Something else?

What genSources command did you run?

**Comment by jaredlll08** [comment]
Closing this due to no reply.
