### ISSUE TITLE
NeoForged issue with MLT

### ISSUE THREAD

**Issue by mysticdrew** [jaredlll08/MultiLoader-Template#31]
Adding this here to link back to the NeoGradle issue tracker regarding the problems. 
https://github.com/neoforged/NeoGradle/issues/19

**Comment by mysticdrew** [comment]
also made an issue in vanilla gradle
https://github.com/SpongePowered/VanillaGradle/issues/123

**Comment by jaredlll08** [comment]
This doesn't seem to be required anymore / at-least I did not run into it when adding NeoForge to the template.

If you are still running into issues with this commit https://github.com/jaredlll08/MultiLoader-Template/commit/ec156b6c83ccd2a890fbb23237c4173ead1dc32c then please let me know and I'll re-open this issue.

**Comment by BlayTheNinth** [comment]
Just for closure and in case anyone else has a slightly diverging template based on this one, the key thing that's preventing the `Cannot add extension with name 'settings', as there is an extension already registered with that name.` error in this template is that it's declaring

```gradle
plugins {
    // ...
    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT' apply(false)
    // ...
}
```

in the root build.gradle, which was added a few months ago:

https://github.com/jaredlll08/MultiLoader-Template/commit/45030884b0009e6b3b9675f07d1d2f853a433b90
