### ISSUE TITLE
[1.19] Unreachable Minecraft packages and classes when using Fabric

### ISSUE THREAD

**Issue by Griefed** [jaredlll08/MultiLoader-Template#32]
Heyo,

I am currently trying to make use of the 1.19 branch of this template in order to create a basic mod which simply adds a couple of blocks.
The Forge-aspect of the template is working as expected, but I am running into a wall when it comes to Fabric.

1. I've cloned the repo
2. ran `Your Project > Common > Tasks > vanilla gradle > decompile`
3. ran  `Your Project > Forge > Tasks > forgegradle runs > genIntellijRuns`

and then went on to add Blocks for 1.19.2 to Fabric as shown [on the Fabric wiki](https://fabricmc.net/wiki/tutorial:blocks) and [on Kaupenjoes Fabric 1.19 Tutorial](https://youtu.be/6DY372RYNfE?si=n5pXL68SSyTgJC3_&t=111).

This is where the trouble begins and I do not know where the problem is:

I can not call `new Identifier(...)`, IntelliJ IDEA can not find or access `net.minecraft.util.Identifier`. My IntelliJ IDEA version is `IntelliJ IDEA 2023.2.4`

I'm using the following verions set in my gradle.properties

```properties
minecraft_version=1.19.2

# Forge
forge_version=43.2.21
forge_loader_version_range=[43,)
forge_version_range=[43,)
minecraft_version_range=[1.19,)

# Fabric
fabric_version=0.76.1+1.19.2
fabric_loader_version=0.14.24
```

Would anyone here happen to know what the cause of this might be, or would anyone be able to help with this?

Cheers,
Griefed

**Comment by jaredlll08** [comment]
The tutorials you are looking at are using the Yarn mappings, https://fabricmc.net/wiki/tutorial:mappings, however this template is using the mappings provided by Mojang themselves, as that is the only way to get the common code compiling and working in both forge and fabric.

The `Identifier` class that you mentioned there, is actually `ResourceLocation`

**Comment by Griefed** [comment]
Thank you very much for helping me out here.
I take it every other class, like `ItemGroups` will then have their corresponding class in the Mojang-mappings, too.

Schweet. That helps a lot! Thanks again!
