### ISSUE TITLE
Package 'net.minecraft.client' does not exist

### ISSUE THREAD

**Issue by Leialoha** [jaredlll08/MultiLoader-Template#40]
### Versions:
- Java: 17.0.8.1 (Eclipse Adoptium 17.0.8.1+1)
- Gradle: 8.1.1 
- Groovy: 3.0.15
- OS: Windows 10 10.0 amd64

### Template:
- Branch: 1.20.2

### Error:
- Gradle Build Output: https://gist.github.com/Leialoha/8a70de015a71bf0c68a7e2568a7fe6b3

![Screenshot 2023-12-20 160717](https://github.com/jaredlll08/MultiLoader-Template/assets/46801087/b9804abd-74aa-4c96-916a-26627cd7731a)

---

This is a fresh start of the MultiLoader Template, I haven't changed a single value I just ran these operations:
- `Your Project > Common > Tasks > vanilla gradle > decompile`
- `Your Project > Forge > Tasks > forgegradle runs > genIntellijRuns`
- `Your Project > Forge > Tasks > forgegradle runs > Client`

**Comment by Leialoha** [comment]
Just to clarify, I can run fabric client no problem.

**Comment by jaredlll08** [comment]
Can you test with the forge MDK and see if that has the same issue

**Comment by Leialoha** [comment]
I have tested the Forge MDK, found out my graphics driver needed to be updated. After updating my driver, the forge SDK ran and displayed the main title screen. However, updating the driver didn't seem to fix the issue above about missing the packages.

**Comment by jaredlll08** [comment]
Can you try running `gradlew build`

**Comment by Leialoha** [comment]
Build Logs: https://gist.github.com/Leialoha/a0285a612f7750919960c71833243365

**Comment by jaredlll08** [comment]
You said this was a fresh clone of the template, but I'm not seeing anything related to the neogradle project, which shouldn't be possible seeing as 1.20.2 was only added with neoforge.

Can you please try a proper fresh clone, with absolutely no changes made to the template, just:
```bash
cd ~/Desktop
git clone https://github.com/jaredlll08/MultiLoader-Template.git
cd MultiLoader-Template
.\gradlew build
```
I have no issues running those commands myself, so I'm really not sure why you would be having issues here.

**Comment by Leialoha** [comment]
Fresh install, no changes: https://gist.github.com/Leialoha/66158b2e79bcdea3e229f91996addee8

**Comment by jaredlll08** [comment]
That still doesn't have the neoforge project.

Could you please open a new command prompt, run those commands, and then provide the output of the full command prompt, not just the gradle command, including the `cd` command itself.

Also the reason I am asking for `cd ~/Desktop` is to eliminate anything that could be causing any sort of problem, like running on a different drive (not that I have experienced any problems with that myself, but you never know what is up with ForgeGradle)

**Comment by Leialoha** [comment]
Fresh install in the `~/Desktop`: https://gist.github.com/Leialoha/03510cae6ad9dba256a99b6e1e2844c5

**Comment by Leialoha** [comment]
After deleting the gradle cache folder `~/.gradle` it builds with no errors
Check the [discord](https://discord.myceliummod.network/) for more info

**Comment by jaredlll08** [comment]
Relevant discord thread:
https://discord.com/channels/752944675425353768/1186408640073175050
