### ISSUE TITLE
Lots of errors and warnings, and a question

### ISSUE THREAD

**Issue by CrypticVerse** [jaredlll08/MultiLoader-Template#48]
I was trying to develop a mod using this template and in the build.gradle files, lots of warnings were coming up about plugins and compileOnly project(":common").
Do not know why this is happening.

And a question:
On other multiloader projects, NOT architectury, when they add a Non-full block with Official Mappings or ParchmentMC, the constructor says public. On my project, these classes have a protected constructor, so I can't use them. Does anyone know why this is happening and how to fix it? I have already run Common/decompile.

**Comment by jaredlll08** [comment]
Which version were you using, the groovy syntax(`build.gradle`), or the kotlin syntax (`build.gradle.kts`)?

The mappings would have nothing to do with the visibility of members, it is possible that those other projects were using access transformers / access wideners, or that Forge itself was making the constructor public, regardless you can use an access widener in common and fabric, and an access transformer in Forge to make the constructor public

**Comment by CrypticVerse** [comment]
I'm using groovy and I also don't know how to use access wideners.

**Comment by CrypticVerse** [comment]
Thank you for your help!

**Comment by CrypticVerse** [comment]
I'm using groovy, don't know why the warnings are popping up.

**Comment by CrypticVerse** [comment]
![Capture](https://github.com/jaredlll08/MultiLoader-Template/assets/143554094/b7c99e45-23f2-4339-89bc-a2d6ddc3e444)

**Comment by jaredlll08** [comment]
I believe you can ignore those warnings, I have never gotten accurate groovy support in an IDE, as long as you can run `gradlew build`, and you get the output jars, it should be working fine, regardless of whatever IDEA thinks the issue is.

**Comment by CrypticVerse** [comment]
Thank you!
