### ISSUE TITLE
Registering Screen handlers?

### ISSUE THREAD

**Issue by CrypticVerse** [jaredlll08/MultiLoader-Template#49]
Registering screen handlers in common module:

Fabric goes like this:
```gradle
    public static final MenuType<MyScreenHandler> MY_SCREEN_HANDLER =
            Registry.register(BuiltInRegistries.MENU, new ResourceLocation(MyMod.MOD_ID, "my_screem"),
                    new ExtendedScreenHandlerType<>(MyScreenHandler::new));
```
And like this in forge:
```gradle
    public static final DeferredRegister<MenuType<?>> MENUS =
            DeferredRegister.create(ForgeRegistries.MENU_TYPES, MyMod.MOD_ID);

    public static final RegistryObject<MenuType<MyScreen>> MY_SCREEN =
            registerMenuType("my_screen", MyScreen::new);


    private static <T extends AbstractContainerMenu> RegistryObject<MenuType<T>> registerMenuType(String name, IContainerFactory<T> factory) {
        return MENUS.register(name, () -> IForgeMenuType.create(factory));
    }

    public static void register(IEventBus eventBus) {
        MENUS.register(eventBus);
    }
```

How do you make this in common? Both use loader-specific resources, and common cannot use these resources.

**Comment by jaredlll08** [comment]
We have an example of the template with registration built in: https://github.com/jaredlll08/MultiLoader-Template/tree/1.18.2/examples/MultiLoader-Template-with-registration

In general we don't really provide help with how to do specific things, rather we can provide help on how things can be abstracted (like using ServiceLoaders for example).

You can ask on the [discord](https://discord.myceliummod.network/) for more generalized help however.
