### ISSUE TITLE
Crash on any ./gradlew command

### ISSUE THREAD

**Issue by CrypticVerse** [jaredlll08/MultiLoader-Template#50]
Crashes with:
  symbol:   class TagKey
  location: class FuelRegistryImpl
C:\Users\myUser\Notebook\common\src\main\java\dev\bookkeepersmc\notebook\registry\content\impl\FuelRegistryImpl.java:117: error: cannot find symbol
    public static void add(Map<Item, Integer> map, TagKey<Item> tag, int i) {

About 150 of these errors, don't know why. Worked fine and then just started with these problems.

**Comment by CrypticVerse** [comment]
Randomly starting working again...

**Comment by CrypticVerse** [comment]
Gives error: ExampleMethod has private access in net.minecraft.~~~. I have this method/class in the accessWidener on common, and can use it, but gradle gives the private method error.

**Comment by jaredlll08** [comment]
can your upload your project somewhere so that I can pull it please.

**Comment by CrypticVerse** [comment]
Sure! I have a repo for it, that is [here](https://github.com/BookkeepersMC/Notebook).

**Comment by CrypticVerse** [comment]
Also gives warnings about any unused method/class with:
File:Java:line: warning no comment. 100 of these for every module

**Comment by jaredlll08** [comment]
You removed the lines from the fabric build.gradle that copies the files from the common project:
https://github.com/jaredlll08/MultiLoader-Template/blob/1.20.4/fabric/build.gradle#L52C1-L54C2

As for the warnings about unused methods / classes, welcome to forge, where you 'need' to recompile the game, and all the warnings from the game's code gets shoved into your terminal.

As far as I'm aware, there is no solution to that, and you should just ignore it.

**Comment by CrypticVerse** [comment]
> Gives error: ExampleMethod has private access in net.minecraft.~~~. I have this method/class in the accessWidener on common, and can use it, but gradle gives the private method error.

Ok so I replaced addFuel with AbstractFurnaceBlockEntity.add(map, item, time), and the Fabric Client launches successfully, but Forge/NeoForge clients and ./gradlew build fail with:
```gradle
    method AbstractFurnaceBlockEntity.add(Map<Item,Integer>,TagKey<Item>,int) is not applicable
      (add(Map<Item,Integer>,TagKey<Item>,int) has private access in AbstractFurnaceBlockEntity)

    method AbstractFurnaceBlockEntity.add(Map<Item,Integer>,ItemLike,int) is not applicable
      (argument mismatch; TagKey<Item> cannot be converted to ItemLike)

C:\Users\MyUser\Notebook\common\src\main\java\dev\bookkeepersmc\notebook\registry\content\impl\FuelRegistryImpl.java:113: error: no suitable method found for add(Map<Item,Integer>,ItemLike,int)
                AbstractFurnaceBlockEntity.add(map, item, time);
```
I added AbstractFurnaceBlockEntity add to my Common accessWidener, and can use it, but gradle and neo/forge fails.

**Comment by jaredlll08** [comment]
Accesswideners aren't applied to the forge / neoforge projects, the only reason they work in Fabric is because of this line <https://github.com/BookkeepersMC/Notebook/blob/master/fabric/build.gradle#L26>, which pulls it from the common project.

Forge and NeoForge use AccessTransformers instead, and are written with a different syntax, so you will need to maintain both an accesswidener and accesstransformer file.


This issue tracker is mainly for issues with the template itself, not for issues with developing Multiloader mods.

If you have any further issues that are unrelated to the template itself, please can you ask them on the discord.

https://discord.myceliummod.network/
