### ISSUE TITLE
1.19 - Unable to resolve gradle dependencies

### ISSUE THREAD

**Issue by godemperoroftheworld** [jaredlll08/MultiLoader-Template#60]
Starting this morning, I'm starting to see an error like this across all my multiloader projects:

I get the same error pulling the 1.19 branches from here and running build.

No changes on my end to any of the `build.gradle` files -- it appears any dependency i put in my `common` module's `build.gradle` will throw a similar error.

```
> Could not resolve all files for configuration ':Common:compileClasspath'.
   > Could not resolve net.minecraft:joined:1.19.2.
     Required by:
         project :common
      > Could not resolve all files for configuration ':common:mergetool'.
         > Could not find net.minecraftforge:mergetool:1.2.3.
           Required by:
               project :common
```

I have the suspicion that `mergetool` is the real culprit for this given all the mess over at forge lately.

**Comment by AzureDoom** [comment]
This is an issue with VanillaGradle due to a recent update to it's snapshots. You need to upgrade to Gradle 8.7 or 8.8

**Comment by godemperoroftheworld** [comment]
Thanks! Should I make a PR to update the 1.19 template here also to have the right gradle version?

**Comment by jaredlll08** [comment]
If you don't mind, please make the PR

**Comment by AzureDoom** [comment]
> If you don't mind, please make the PR

PR sent for this now!

**Comment by jaredlll08** [comment]
Fixed by https://github.com/jaredlll08/MultiLoader-Template/pull/62
