### ISSUE TITLE
1.20.2 gradle problems with common

### ISSUE THREAD

**Issue by x-j0nnay-x** [jaredlll08/MultiLoader-Template#67]
every time i'm trying to start up a project the common main keeps getting these errors 
`
:common:main: Could not find org.spongepowered:mixin:0.8.5.
Required by:
    project :common
:common:main: Could not find com.google.code.findbugs:jsr305:3.0.1.
Required by:
    project :common
:common:main: Could not resolve net.minecraft:joined:1.20.2.
Required by:
    project :common
:common:test: Could not find com.google.code.findbugs:jsr305:3.0.1.
Required by:
    project :common
:common:test: Could not resolve net.minecraft:joined:1.20.2.
Required by:
    project :common
`
when trying to run the decompile i get
`Execution failed for task ':common:decompile'.
> Failed to calculate the value of task ':common:decompile' property 'javaLauncher'.
   > Failed to calculate the value of property 'languageVersion'.
      > Could not resolve all artifacts for configuration ':common:decompiler'.
         > Could not find org.vineflower:vineflower:1.10.1.
           Required by:
               project :common
`

**Comment by jaredlll08** [comment]
Update gradle to 8.8, VanillaGradle made changes that require a newer gradle.
