### ISSUE TITLE
Show an example of calling back into platform specific code

### ISSUE THREAD

**Issue by williewillus** [jaredlll08/MultiLoader-Template#7]
In Patchouli and Botania, we use a serviceloader interface called `IXplatAbstractions`, implemented once by each loader, to allow down calls from Common code back into loader-specific code. This is probably something that is needed often enough that this template should probably have an example of it.

**Comment by Darkhax** [comment]
Yeah, this is something I use a lot in Bookshelf and a few other projects so there is definitely some value in documenting this. I will talk to Jared later today about building up the wiki.
