### ISSUE TITLE
No "runs" generated for Forge

### ISSUE THREAD

**Issue by MrAmericanMike** [jaredlll08/MultiLoader-Template#71]
Following the guide I see that at the end it mentions:

```
 Under the `Application` category there should now be options to run Fabric and NeoForge projects.
```

Is there a reason as to why the options to run Forge are not generated?

**Comment by GirafiStudios** [comment]
Because ForgeGradle doesn´t allow for the genIntelliJRuns (or genEclipseRuns I guess) task to run automatically on setup

**Comment by jaredlll08** [comment]
I don't know if ForgeGradle has anything that actually stops them from generating the runs automatically, they just don't bother to.
