### ISSUE TITLE
Resources not available when launching Fabric in dev environment

### ISSUE THREAD

**Issue by copygirl** [jaredlll08/MultiLoader-Template#73]
I've cloned the 1.20.1 branch of this project and set up my existing Forge project with it. It's relatively simple, and the only data in it is me overriding the Vanilla spawner to allow for silk touch touching when a config setting is enabled.

- Works when launching with Forge.
- Works after building and using in a launcher.
- ~~Works if placing the data file in `fabric/` rather than `common/`.~~
- ~~Unsure if this only applies to overriding Vanilla data.~~
- ~~Unsure if this also affects assets, not just data.~~

Here's the branch on my repository with the WIP multi loader port:
https://github.com/copygirl/exhausted-spawners/tree/wip/multi-loader

I assume this has something to do with the Gradle setup, and I have never been able to speak Gradle.

**Comment by copygirl** [comment]
Okay I just got around to testing some more, and indeed language files aren't available either. For my own mod, not overriding Vanilla files.

**Comment by copygirl** [comment]
@jaredlll08 Hey I saw you ping me on Discord. Unfortunately due to phone verification requirements I don't have the ability to post and I couldn't DM you either. If you're okay with it, I believe giving me any random role would allow me to get around the verification.

**Comment by copygirl** [comment]
This appears to just be an issue with the VSCode launch options, which understandably aren't supported. Using `./gradlew runClient` works as intended.

**Comment by jaredlll08** [comment]
Some more info, the vscode gradle plugin is based on Eclipse BuildShip, so it suffers from the [same issues as Eclipse](https://github.com/jaredlll08/MultiLoader-Template?tab=readme-ov-file#eclipse)
