### ISSUE TITLE
Some recipes don't work.

### ISSUE THREAD

**Issue by SaintSaka** [jaredlll08/MultiLoader-Template#76]
Minecraft 1.20.1. Fabric. Mod v1.5.7

![imagem_2024-10-03_131833458](https://github.com/user-attachments/assets/2325a8af-47f8-4f35-9545-f2636dc6db42)

**Comment by jaredlll08** [comment]
I think you have the wrong project, that is not a vanilla recipe (iirc) and this project doesn't have any recipes.
