### ISSUE TITLE
The Mixin Plugin doesn't work?

### ISSUE THREAD

**Issue by Yefancy** [jaredlll08/MultiLoader-Template#77]
<img width="765" alt="image" src="https://github.com/user-attachments/assets/6ca2385f-75a3-408f-aa14-bb75042e1132">

MultiLoader-Template works really amazing. However, the mixin plugin seems doesn't wirk even it does work.

version: 1.21

**Comment by jaredlll08** [comment]
We haven't had any reports of the MCDev plugin having issues, just to confirm, which "Mixin Plugin" are you using?

**Comment by Yefancy** [comment]
Im using the latest MCDev Plugin.
environment: macos, IDEA
version: latest 1.21 branch
reproduce:
1. clone the 1.21 branch
2. fix the dependency issue by #75 
3. open the mixin files (any of them, common, fabric, neoforge, ....)
4. methods and fields can't be detected by the idea plugin, while it can be run without any issue.

**Comment by jaredlll08** [comment]
Does it work in a non multiloader environment?

I think this may be an issue for the MCDev authors

**Comment by Yefancy** [comment]
MCDev works well in a platform standalone project, as well as an architectury project in my env. BTW, when I switch to my other branch which is using the architectury prject and switch it back to the multiloader, the MCDev works again until I refresh(sync) my gradle again.

**Comment by jaredlll08** [comment]
That definitely sounds like a bug with the plugin, I would report it to them.

**Comment by Yefancy** [comment]
it got fixed with the lastest IDEA installed
