### ISSUE TITLE
Fabric is not working 1.21

### ISSUE THREAD

**Issue by Byllfighter** [jaredlll08/MultiLoader-Template#78]
Fabric mod is working on runClient, but when Minecraft launches with generated jar file, it has ClassNotFoundException for everything.

**Comment by jaredlll08** [comment]
Do you have log file?

**Comment by Byllfighter** [comment]
I also tested it on MultiLoader Template without changes.
[latest.log](https://github.com/user-attachments/files/17401265/latest.log)
[crash-2024-10-16_21.41.51-client.txt](https://github.com/user-attachments/files/17401267/crash-2024-10-16_21.41.51-client.txt)

**Comment by jaredlll08** [comment]
What jar file are you trying to run? 
can you upload it here please

**Comment by Byllfighter** [comment]
[examplemod-fabric-1.21-1.0.0-dev.jar.zip](https://github.com/user-attachments/files/17444273/examplemod-fabric-1.21-1.0.0-dev.jar.zip)

**Comment by jaredlll08** [comment]
where are you getting a `-dev` jar from??

running the following:
```bash
git clone https://github.com/jaredlll08/MultiLoader-Template
cd MultiLoader-Template
./gradlew build
```
results in the following files in `fabric/build/libs/`:
```
examplemod-fabric-1.21-1.0.0-javadoc.jar
examplemod-fabric-1.21-1.0.0-sources.jar
examplemod-fabric-1.21-1.0.0.jar
```

**Comment by Byllfighter** [comment]
When I used `build` it didn't even create the "libs" folder. I got `-dev` jar from "devlibs" folder. I found that when I use `remapJar` task it creates a normal working jar file in "libs" folder.

**Comment by jaredlll08** [comment]
Okay, well a dev jar is not going to work in production.

Please follow the steps in my last message and upload the log file from the `./gradlew build`

`build` should call `remapJar` unless something funky is going on.

**Comment by Byllfighter** [comment]
It looks like the problem occurs because the Gradle Home path had special characters. I changed it and it worked fine.

**Comment by jaredlll08** [comment]
Okay, well there is nothing I can do to solve that, that is either and issue with Gradle or one of the modloader plugins.
