### ISSUE TITLE
[ Question ] Cannot locate tasks

### ISSUE THREAD

**Issue by Xelbayria** [jaredlll08/MultiLoader-Template#81]
- Minecraft 1.20.1
- IDEA Community Edition 2024.3
- Gradle v8.10.2

I finished importing all of the library and haven't configure the project's properties (group, mod_name, so on) in `gradle.properties`. I ran a CLIENT for forge and got an error below: 
```
Cannot locate tasks that match ':forge:prepareMinecraft' as task 'prepareMinecraft' is ambiguous in project ':forge'
```

I've tried other methods like `forge:prepareClientCompile` and it still provide the same error as above. 

FABRIC CLIENT is working properly. What's the solution to get FORGE CLIENT working properly?

## UPDATED: 

Somehow the `genIntellijRuns` got the configuration wrong.  the configuration of **forge Client** has the set of 

Before Launch: 
`1. Build 2. Run Gradle task 'ExampleMod: :forge:prepareClientCompile'`

in the end, i had to correct it to `:forge:Client` and got Minecraft Client launching with FORGE. 

This should be fixed in Multi-loader Template

**Comment by jaredlll08** [comment]
> Somehow the genIntellijRuns got the configuration wrong. the configuration of forge Client has the set of

ForgeGradle provides the genIntellijRuns command and generates the files.

I can confirm that when I run the command on my machine, I get the following Before Launch:
```
1. Build 2. Run Gradle task 'ExampleMod: :forge:prepareClientCompile'
```
and the game loads perfectly fine.

Report this to ForgeGradle and see what they say about it, but I don't believe there is anything I can do in the template to fix this.
