### ISSUE TITLE
1.6.4 - 1.12.2 support (legacy fabric)

### ISSUE THREAD

**Issue by millennIumAMbiguity** [jaredlll08/MultiLoader-Template#82]
it would be nice to have branches for legacy and cursed loaders.

even if there is only fabric, having the common files will help with multi-version support.

**Comment by jaredlll08** [comment]
This template is specifically for targeting multiple mod loaders from a common code base, this is only possible if all loaders use the mappings provided my mojang, which only go back to 1.14.
In all versions before 1.17, forge either used MCP names, or a cursed combination of MCP class names but mojmap method / field names, meaning that it can't work off a common non forge codebase.

Along with that, both "common" minecraft providers that we have used (VanillaGradle and ModDevGradle) have limited version support, VanillaGradle strictly works with mojmaps, so 1.14+, and ModDevGradle, even with their legacy plugin, only works on 1.17+, so there is no good way to provide a common minecraft artifact for the older versions you requested.
